[package]
name = "facilitation"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
