use async_trait::async_trait;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct FacilitationRequest {
    pub room_id: String,
    pub requested_by: String,
    pub prompt: String,
    pub visible_context: Vec<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct FacilitationResponse {
    pub id: String,
    pub room_id: String,
    pub generated_by: String,
    pub disclosure: String,
    pub suggestion: String,
    pub uncertainty: String,
    pub considered: Vec<String>,
    pub missing_context: Vec<String>,
    pub generated_at: DateTime<Utc>,
    pub accepted: Option<bool>,
}

#[derive(Debug, thiserror::Error)]
pub enum FacilitationError {
    #[error("facilitation is disabled")]
    Disabled,
    #[error("prompt is empty")]
    EmptyPrompt,
}

#[async_trait]
pub trait FacilitationProvider: Send + Sync {
    async fn assist(
        &self,
        input: FacilitationRequest,
    ) -> Result<FacilitationResponse, FacilitationError>;
}

#[derive(Default)]
pub struct MockFacilitationProvider;

#[async_trait]
impl FacilitationProvider for MockFacilitationProvider {
    async fn assist(
        &self,
        input: FacilitationRequest,
    ) -> Result<FacilitationResponse, FacilitationError> {
        if input.prompt.trim().is_empty() {
            return Err(FacilitationError::EmptyPrompt);
        }

        Ok(FacilitationResponse {
            id: format!("facilitation-{}", Utc::now().timestamp_micros()),
            room_id: input.room_id,
            generated_by: "MockFacilitationProvider".to_string(),
            disclosure: "Generated by AI; participants may revise or reject it.".to_string(),
            suggestion: "One possible clarification question: When you say community control, who should approve technical decisions and who should hold the project records?".to_string(),
            uncertainty: "This suggestion may miss local political or historical context.".to_string(),
            considered: input.visible_context,
            missing_context: vec![
                "Power differences between participants were not inferred.".to_string(),
                "Local language nuance should be checked by the speakers.".to_string(),
            ],
            generated_at: Utc::now(),
            accepted: None,
        })
    }
}

#[derive(Default)]
pub struct NoFacilitationProvider;

#[async_trait]
impl FacilitationProvider for NoFacilitationProvider {
    async fn assist(
        &self,
        _input: FacilitationRequest,
    ) -> Result<FacilitationResponse, FacilitationError> {
        Err(FacilitationError::Disabled)
    }
}

#[cfg(test)]
mod tests {
    use super::{FacilitationProvider, FacilitationRequest, MockFacilitationProvider};

    #[tokio::test]
    async fn mock_facilitator_never_declares_consensus() {
        let response = MockFacilitationProvider
            .assist(FacilitationRequest {
                room_id: "room".to_string(),
                requested_by: "amara".to_string(),
                prompt: "clarify".to_string(),
                visible_context: vec!["Translation may be incomplete".to_string()],
            })
            .await
            .unwrap();

        assert!(!response.suggestion.contains("Both sides agree"));
        assert!(response
            .disclosure
            .contains("participants may revise or reject"));
    }
}
